### ISSUE TITLE
Can this method running online?

### ISSUE THREAD

**Issue by Ryuk17** [lixilinx/EnhancedPHAT#1]

**Comment by lixilinx** [comment]
Short answer: yes.

This method is virtually as simple as PHAT (compared with methods like MUSIC). Please refer to eq (10) in the paper. Online implementation may looks like:

1, you may update the auto and cross correlations between the two mic signals for each bin when speech is active as

r1 <-- 0.9*r1 + 0.1*X1*conj(X1)
r2 <-- 0.9*r2 + 0.1*X2*conj(X2)
c12 <-- 0.9*c12 + 0.1*X1*conj(X2)

2, then the estimated coherence is

gamma_x_hat = c12/sqrt(r1*r2)

3, then you use eq (10) to correct the phase bias in gamma_x_hat to get gamma_s_ml

4, finally, location of the max of ifft(gamma_s_ml) gives the delay estimation.
